// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvrChCNEAEfOLc-iWhH1h6Gw-Lqe4Zriw',
    appId: '1:1050329770640:web:2d17b3950be668ddca8615',
    messagingSenderId: '1050329770640',
    projectId: 'session8-1563e',
    authDomain: 'session8-1563e.firebaseapp.com',
    storageBucket: 'session8-1563e.appspot.com',
    measurementId: 'G-S8GP9NPECM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpIsLfiwjkDbbKqJAaRZxS8ywticxFHcQ',
    appId: '1:1050329770640:android:57e483fd66cd8498ca8615',
    messagingSenderId: '1050329770640',
    projectId: 'session8-1563e',
    storageBucket: 'session8-1563e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWjKjJoDXVS-B0jDDLErvjcFEeMwcjowo',
    appId: '1:1050329770640:ios:c25095aac58bc397ca8615',
    messagingSenderId: '1050329770640',
    projectId: 'session8-1563e',
    storageBucket: 'session8-1563e.appspot.com',
    iosBundleId: 'com.example.session6',
  );

}